# Generated by Django 3.0.5 on 2022-07-05 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(default=None, max_length=30, unique=True)),
                ('pwd', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('courseid', models.CharField(max_length=20)),
                ('program_year', models.CharField(max_length=20)),
                ('number_of_TA', models.IntegerField()),
            ],
            options={
                'unique_together': {('courseid', 'program_year')},
            },
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=8)),
                ('mail', models.EmailField(max_length=30, unique=True)),
                ('an', models.BooleanField(default=False)),
                ('cid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Main.course')),
            ],
        ),
        migrations.CreateModel(
            name='ta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=8)),
                ('mail', models.EmailField(max_length=30, unique=True)),
                ('year', models.IntegerField()),
                ('star', models.IntegerField(default=0)),
                ('status', models.CharField(default='Not Assigned', max_length=12)),
                ('an', models.BooleanField(default=False)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.course')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=8)),
                ('mail', models.EmailField(max_length=30)),
                ('batch', models.IntegerField()),
                ('sid', models.IntegerField()),
                ('cid', models.ManyToManyField(to='Main.course')),
            ],
        ),
        migrations.CreateModel(
            name='stipendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Not approved yet', 'Not approved yet'), ('Disapproaaved', 'Disapproved')], default='Not approved yet', max_length=20)),
                ('message', models.CharField(blank=True, max_length=100)),
                ('CourseObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.course')),
                ('FacultyObj', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='Main.faculty')),
                ('TAObj', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='Main.ta')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, max_length=1)),
                ('CourseObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.course')),
                ('TAObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.ta')),
                ('studentObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.student')),
            ],
        ),
    ]
