# Generated by Django 4.0.4 on 2022-07-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20220706_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
