# Generated by Django 4.0.4 on 2022-07-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_rating_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ta',
            old_name='star',
            new_name='ratings',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='status',
        ),
    ]
