# Generated by Django 3.0.14 on 2022-07-22 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_rename_star_ta_ratings_remove_rating_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferenced', models.BooleanField(default=False, verbose_name='Preferenced')),
                ('TAID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.ta')),
                ('facultyID', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='Main.faculty')),
            ],
        ),
    ]
