# Generated by Django 3.0.14 on 2022-07-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='preferenced',
        ),
        migrations.AddField(
            model_name='preferences',
            name='preference',
            field=models.IntegerField(default=0),
        ),
    ]
